### PR TITLE
Add missing tiles to DSS2Red survey

### PR DESCRIPTION
**Pull request by adl1995**
I added some tiles (FITS / JPEG) that are required for the drawing process.

### CODE REVIEW

**Comment by cdeil** [comment]
Remove `datasets/samples/DSS2Red/Norder3/Dir0/urls.txt~`.

And probably also `datasets/samples/DSS2Red/Norder3/Dir0/urls.txt` should be removed, no?
(is it something you just made to download, or is it something in HiPS / that we'll support eventually?

**Comment by adl1995** [comment]
Just updated. Please check.

**Comment by cdeil** [comment]
OK, merging now.

@tboch - FYI: Adeel is adding these tiles as they are the ones ((hopefully)) for the sky image centered on the Galactic center that we choose for the `draw_sky_image` test in https://github.com/hipspy/hips/pull/30 .

**Comment by tboch** [comment]
@cdeil: actually, some of these tiles seem to be quite far from the Galactic center, I think there might be some confusion between equatorial and galactic coordinates as we have seen yesterday during the telecon.

**Comment by cdeil** [comment]
I didn't check, yes, probably @adl1995 added some tiles we don't really need.
Maybe we just leave them in and @adl1995 - if you're still missing tiles for the tests, make new PRs adding the right ones.
Alternatively, @tboch, if you prefer, of course feel free to remove tiles that shouldn't really be needed for tests / docs from this repo again.

**Comment by tboch** [comment]
I'm fine leaving them in at the time. I might do some cleanup once we have a first version running as expected.

**Pull request merged**
